language: python

jobs:
  include:
    - services: docker
      arch: arm64

env:
  global:
    - TWINE_USERNAME=__token__

install:
  - python3 -m pip install cibuildwheel==1.5.2

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
