on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
        exclude:
          - os: windows-latest
            python-version: 3.5
          - os: windows-latest
            python-version: 3.6

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install wheel twine
        pip install -e '.[dev]'

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  build_manylinux2010:
    name: Create manylinux2010 Release

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64:latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install wheel twine
        pip install -e '.[dev]'

    - name: Build
      run: |
        /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
        /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
        /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
        /opt/python/cp35-cp35mu/bin/python setup.py bdist_wheel
        /opt/python/cp36-cp36mu/bin/python setup.py bdist_wheel
        /opt/python/cp37-cp37mu/bin/python setup.py bdist_wheel
        /opt/python/cp38-cp38/bin/python setup.py bdist_wheel

    # - name: Build and publish
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     python setup.py sdist
    #     twine upload dist/*
